output          data_req    ,
    output          data_wr     ,
    output   [1 :0] data_size   ,
    output   [31:0] data_addr   ,
    output   [31:0] data_wdata  ,
    input  [31:0] data_rdata  ,
    input         data_addr_ok,
    input         data_data_ok,

    //ar
    output  [3 :0] axi_arid   ,
    output  [31:0] axi_araddr ,
    output  [7 :0] axi_arlen  ,
    output  [2 :0] axi_arsize ,
    output  [1 :0] axi_arburst,
    output  [1 :0] axi_arlock ,
    output  [3 :0] axi_arcache,
    output  [2 :0] axi_arprot ,
    output         axi_arvalid,
    input        axi_arready,
    //r
    input [3 :0] axi_rid    ,
    input [31:0] axi_rdata  ,
    input [1 :0] axi_rresp  ,
    input        axi_rlast  ,
    input        axi_rvalid ,
    output         axi_rready ,
    //aw
    output  [3 :0] axi_awid   ,
    output  [31:0] axi_awaddr ,
    output  [7 :0] axi_awlen  ,
    output  [2 :0] axi_awsize ,
    output  [1 :0] axi_awburst,
    output  [1 :0] axi_awlock ,
    output  [3 :0] axi_awcache,
    output  [2 :0] axi_awprot ,
    output         axi_awvalid,
    input        axi_awready,
    //w
    output  [3 :0] axi_wid    ,
    output  [31:0] axi_wdata  ,
    output  [3 :0] axi_wstrb  ,
    output         axi_wlast  ,
    output         axi_wvalid ,
    input        axi_wready ,
    //b
    input [3 :0] axi_bid    ,
    input [1 :0] axi_bresp  ,
    input        axi_bvalid ,
    output         axi_bready 